# Generated by Django 3.1.3 on 2020-11-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='问卷标题')),
                ('result', models.JSONField(default=[], verbose_name='调研结果')),
                ('user', models.CharField(max_length=64, verbose_name='调研人员')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问卷调研结果',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='问卷标题')),
                ('survey_number', models.IntegerField(default=0, verbose_name='数据库地址')),
                ('completed_number', models.IntegerField(default=0, verbose_name='调研人数')),
                ('users', models.CharField(max_length=128, verbose_name='参与调查人员')),
                ('content', models.JSONField(default=[], verbose_name='问卷内容')),
                ('status', models.BooleanField(default=False, verbose_name='问卷状态')),
                ('start_at', models.DateTimeField(verbose_name='问卷开始时间')),
                ('end_at', models.DateTimeField(verbose_name='问卷结束时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问卷管理',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('telephone', models.CharField(max_length=64, verbose_name='地址')),
                ('questions', models.CharField(max_length=64, verbose_name='调研问卷')),
                ('token', models.CharField(max_length=128, verbose_name='token')),
                ('roles', models.CharField(default='', max_length=255, verbose_name='权限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户列表',
            },
        ),
    ]
