# Generated by Django 3.1.3 on 2020-11-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.JSONField(default=[], verbose_name='权限'),
        ),
    ]
