# Generated by Django 3.1.3 on 2020-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201118_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='users',
            field=models.JSONField(default=[], verbose_name='参与调查人员'),
        ),
    ]
