# Generated by Django 3.1.3 on 2020-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201118_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='users',
            field=models.CharField(max_length=128, verbose_name='参与调查人员'),
        ),
    ]
