# Generated by Django 3.1.3 on 2020-11-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201118_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='uid',
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='result',
            field=models.JSONField(default=list, verbose_name='调研结果'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.JSONField(default=list, verbose_name='问卷内容'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.JSONField(default=list, verbose_name='权限'),
        ),
    ]
