# Generated by Django 3.1.3 on 2020-11-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201119_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='section_score',
            field=models.JSONField(default=list, verbose_name='分部总分'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='测评表总分'),
        ),
    ]
