# Generated by Django 3.1.3 on 2020-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201126_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='section_score',
        ),
        migrations.AddField(
            model_name='questionresult',
            name='content_score_list',
            field=models.JSONField(default=list, verbose_name='分项总分'),
        ),
    ]
