# Generated by Django 3.1.3 on 2020-11-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201126_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.questions'),
            preserve_default=False,
        ),
    ]
