# Generated by Django 3.1.3 on 2020-12-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_statisticsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='评价数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'verbose_name': '评价管理',
            },
        ),
    ]
